# Make a copy of this file called database.yml with the real database credentials below
:development: &defaults
  :adapter: mysql
  :database: nancy_development
  :username: nancy
  :password: 
  :host: localhost

:test:
  <<: *defaults
  :database: nancy_test

:production:
  <<: *defaults
  :database: nancy_production